[package]
name = "bevy_rx"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_app = "0.12"
bevy_ecs = "0.12"
bevy_utils = "0.12"

[dev-dependencies]
# bevy = { version = "0.12", default_features = false }
